import type { Metadata } from "next";
import "./globals.css";
import { GeistPixelLine } from "geist/font/pixel";
import { ThemeProvider } from "./components/providers/theme-provider";

export const metadata: Metadata = {
  title: "Dead Pixel Icon Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${GeistPixelLine.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
