import {
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CopyIcon,
  CrossIcon,
  HeartIcon,
  HomeIcon,
  MenuIcon,
  MinusIcon,
  MoonIcon,
  PlusIcon,
  RefreshIcon,
  SearchIcon,
  SettingsIcon,
  SunIcon,
} from "dead-pixel-icons";
import { type IconData } from "./icons-section";

export const ICONS_DATA: IconData[] = [
  {
    id: 0,
    title: "Settings",
    name: "SettingsIcon",
    icon: SettingsIcon,
  },
  {
    id: 1,
    title: "Copy",
    name: "CopyIcon",
    icon: CopyIcon,
  },
  {
    id: 2,
    title: "Moon",
    name: "MoonIcon",
    icon: MoonIcon,
  },
  {
    id: 3,
    title: "Sun",
    name: "SunIcon",
    icon: SunIcon,
  },
  {
    id: 4,
    title: "Search",
    name: "SearchIcon",
    icon: SearchIcon,
  },
  {
    id: 5,
    title: "Cross",
    name: "CrossIcon",
    icon: CrossIcon,
  },
  {
    id: 6,
    title: "Plus",
    name: "PlusIcon",
    icon: PlusIcon,
  },
  {
    id: 7,
    title: "Minus",
    name: "MinusIcon",
    icon: MinusIcon,
  },
  {
    id: 8,
    title: "Heart",
    name: "HeartIcon",
    icon: HeartIcon,
  },
  {
    id: 9,
    title: "Home",
    name: "HomeIcon",
    icon: HomeIcon,
  },
  {
    id: 10,
    title: "Menu",
    name: "MenuIcon",
    icon: MenuIcon,
  },
  {
    id: 11,
    title: "Arrow Up",
    name: "ArrowUpIcon",
    icon: ArrowUpIcon,
  },
  {
    id: 12,
    title: "Arrow Down",
    name: "ArrowDownIcon",
    icon: ArrowDownIcon,
  },
  {
    id: 13,
    title: "Arrow Left",
    name: "ArrowLeftIcon",
    icon: ArrowLeftIcon,
  },
  {
    id: 14,
    title: "Arrow Right",
    name: "ArrowRightIcon",
    icon: ArrowRightIcon,
  },
  {
    id: 15,
    title: "Chevron Up",
    name: "ChevronUpIcon",
    icon: ChevronUpIcon,
  },
  {
    id: 16,
    title: "Chevron Down",
    name: "ChevronDownIcon",
    icon: ChevronDownIcon,
  },
  {
    id: 17,
    title: "Chevron Left",
    name: "ChevronLeftIcon",
    icon: ChevronLeftIcon,
  },
  {
    id: 18,
    title: "Chevron Right",
    name: "ChevronRightIcon",
    icon: ChevronRightIcon,
  },
  {
    id: 19,
    title: "Refresh",
    name: "RefreshIcon",
    icon: RefreshIcon,
  },
];
